###
POST http://localhost:4000/
Content-Type: application/json


 {
  "username": "username4",
  "password": "password4",
  "email": "mail4@gmail.com",
  "first_name": "fname4",
  "last_name": "lname4",
  "dob": "2003-12-04"
}

###
4. access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDEsImV4cCI6MTY5ODU2OTQ0MX0.4wLY6E4eC6DMnSslAn6-mH7Xvo8VXe9tJYLyQeDOzKw 
4. refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDF9.bkV0vWhpnpjlNVtC_uLrSsEPTbRL2H6LjnImlK9brCo 
###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "username4",
  "password": "password4"
}

###

POST http://localhost:4000/about
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDEsImV4cCI6MTY5ODU2OTQ0MX0.4wLY6E4eC6DMnSslAn6-mH7Xvo8VXe9tJYLyQeDOzKw 

{
  "about": "Hello I am person 4."
}
###
POST http://localhost:4000/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDF9.bkV0vWhpnpjlNVtC_uLrSsEPTbRL2H6LjnImlK9brCo"

}

###

# get profile details
GET http://localhost:4000/username4 HTTP/1.1



# add post
# POST http://localhost:4000/post/upload
# {
#   "postTitle": "dfd",
#   "postContent": "dfdfddf"
# }


###
# get all post of username
GET http://localhost:4000/post/username/username4

###

# delete post give post id
DELETE http://localhost:4000/post/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg0MjIwNzEsImV4cCI6MTY5ODQyMzg3MX0.R1hQCxbVzTMzqewT-ga7ezg3GBIlA26hu4kDHcC57N4 

###
# get single post by id
GET http://localhost:4000/post/postId/1

###

GET http://localhost:4000/post/feeds

###

# like dislike post

POST http://localhost:4000/post/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDEsImV4cCI6MTY5ODU2OTQ0MX0.4wLY6E4eC6DMnSslAn6-mH7Xvo8VXe9tJYLyQeDOzKw  

{
  "postId": "3"
}

###
GET http://localhost:4000/post/likedposts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njc2NDEsImV4cCI6MTY5ODU2OTQ0MX0.4wLY6E4eC6DMnSslAn6-mH7Xvo8VXe9tJYLyQeDOzKw  

###
POST http://localhost:4000/comment/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VybmFtZTQiLCJpYXQiOjE2OTg1Njg2NDgsImV4cCI6MTY5ODU3MDQ0OH0.sRbb4ipJkDaOwm4SWdhrz8ltp2FbJ-r26zOR6TD_BlQ 

{
  "postId": "4",
  "commentContent": "Greate Hello World"
}

###


GET http://localhost:4000/comment/last HTTP/1.1
Content-Type: application/json

{
  "postId": "4"
}
###


GET http://localhost:4000/comment/all HTTP/1.1
Content-Type: application/json

{
  "postId": "1"
}